'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const { glob } = require('glob');
const { calculateCost } = require('./pricing');

const CLAUDE_DIR = path.join(os.homedir(), '.claude', 'projects');

async function findSessionFiles(baseDir = CLAUDE_DIR) {
  if (!fs.existsSync(baseDir)) return [];
  const files = await glob('**/*.jsonl', { cwd: baseDir, absolute: true });
  return files;
}

function parseJsonlFile(filePath) {
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  const entries = [];
  for (const line of lines) {
    const t = line.trim();
    if (!t) continue;
    try { entries.push(JSON.parse(t)); } catch { /* skip */ }
  }
  return entries;
}

function extractProjectName(filePath, baseDir) {
  const rel = path.relative(baseDir, filePath);
  const parts = rel.split(path.sep);
  if (parts.length >= 2) {
    return parts[0].replace(/^-/, '').replace(/-/g, '/').replace(/^\//, '') || 'Unknown Project';
  }
  return 'Unknown Project';
}

/** Extract plain text from a message content field */
function extractText(content) {
  if (!content) return '';
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content
      .filter(c => c.type === 'text' && c.text)
      .map(c => c.text)
      .join(' ');
  }
  return '';
}

/** Strip <ide_selection>…</ide_selection> blocks injected by IDE integrations */
function cleanIdeSelection(text) {
  if (!text) return text;
  // Remove complete <ide_selection>...</ide_selection> blocks (possibly multiline)
  let t = text.replace(/<ide_selection>[\s\S]*?<\/ide_selection>/gi, '');
  // Remove any orphan open/close tags
  t = t.replace(/<\/?ide_selection[^>]*>/gi, '');
  // Also remove the common "This may or may not be related to the current task" suffix
  t = t.replace(/\.?\s*This may or may not be related to the current task\.?/gi, '');
  return t.replace(/\s+/g, ' ').trim();
}

/**
 * Maps the `entrypoint` field to a human-readable client label.
 * Known values observed in Claude Code JSONL files.
 */
function resolveClient(entrypoint) {
  if (!entrypoint) return 'Terminal CLI';
  switch (entrypoint) {
    case 'cli':            return 'Terminal CLI';
    case 'vscode':         return 'VS Code';
    case 'jetbrains':      return 'JetBrains';
    case 'desktop':        return 'Desktop App';
    case 'remote':         return 'Web (claude.ai)';
    case 'remote_mobile':  return 'Mobile (claude.ai)';
    case 'remote_web':     return 'Web (claude.ai)';
    default:               return entrypoint;
  }
}

/** Returns true if this user message is a real human prompt (not a tool result) */
function isUserTextMessage(entry) {
  if (entry.type !== 'user' || !entry.message) return false;
  const content = entry.message.content;
  if (typeof content === 'string') return content.trim().length > 0;
  if (Array.isArray(content)) {
    return content.some(c => c.type === 'text' && c.text && c.text.trim().length > 0);
  }
  return false;
}

/**
 * Patterns for Claude Code's internal automated messages.
 * These are NOT user queries — they are system-generated by Claude Code's
 * /compact summarizer and session-continuation mechanisms.
 */
const AUTOMATION_PATTERNS = [
  /^your task is to create a detailed summary of the conversation so far/i,
  /^this session is being continued from a previous conversation/i,
  /^<claude-codex-session-continuation>/i,
  /^<task>.*create.*summary/i,
  /^\s*<\/?[a-z][-a-z]*>/i,   // entries starting with XML/HTML tags
];

/** Returns a short label if this prompt is an automated Claude Code operation, else null. */
function automationLabel(text) {
  if (!text) return null;
  const t = text.trim();
  if (/^your task is to create a detailed summary/i.test(t)) return '[Auto: Conversation Summary]';
  if (/^this session is being continued/i.test(t)) return '[Auto: Session Continuation]';
  if (/^<claude-codex-session-continuation>/i.test(t)) return '[Auto: Session Continuation]';
  if (/^\s*<[a-z]/.test(t)) return '[Auto: System Message]';
  return null;
}

/**
 * Build full analytics dataset.
 * Key fix: two-pass global UUID deduplication — keeps the entry with the
 * highest output_tokens for each UUID (the final, complete streaming entry).
 */
async function buildAnalytics(baseDir = CLAUDE_DIR, opts = {}) {
  const files = await findSessionFiles(baseDir);

  // ── Pass 1: collect every assistant+usage entry, deduplicated by UUID ──────
  // For each UUID keep the entry with the most output_tokens (= most complete).
  const byUuid = new Map();  // uuid -> { entry, sessionId, projectName, filePath }
  const userByUuid = new Map();   // uuid -> user entry (for prompt lookup)
  // Track first text prompt per session
  const sessionFirstPrompt = new Map(); // sessionId -> string
  const sessionClientMap = new Map();   // sessionId -> client label
  const sessionPromptCount = new Map(); // sessionId -> count of real user prompts

  for (const filePath of files) {
    const entries = parseJsonlFile(filePath);
    const sessionId = path.basename(filePath, '.jsonl');
    const projectName = extractProjectName(filePath, baseDir);

    for (const entry of entries) {
      if (!entry.uuid) continue;

      if (isUserTextMessage(entry)) {
        userByUuid.set(entry.uuid, entry);
        const rawText = extractText(entry.message.content).replace(/\s+/g, ' ').trim();
        const text = cleanIdeSelection(rawText);
        if (text && !automationLabel(text)) {
          // Count real user prompts per session
          sessionPromptCount.set(sessionId, (sessionPromptCount.get(sessionId) || 0) + 1);
          // Track first NON-automated prompt
          if (!sessionFirstPrompt.has(sessionId)) {
            sessionFirstPrompt.set(sessionId, text.slice(0, 120));
          }
        }
      }

      // Track entrypoint (client type) per session — use first occurrence
      if ((entry.type === 'user' || entry.type === 'assistant') && entry.entrypoint) {
        if (!sessionClientMap.has(sessionId)) {
          sessionClientMap.set(sessionId, resolveClient(entry.entrypoint));
        }
      }

      if (entry.type === 'assistant' && entry.message?.usage) {
        const existing = byUuid.get(entry.uuid);
        const newOut = entry.message.usage.output_tokens || 0;
        const oldOut = existing ? (existing.entry.message.usage.output_tokens || 0) : -1;
        // Keep the entry with the highest output_tokens (most complete)
        if (newOut >= oldOut) {
          byUuid.set(entry.uuid, { entry, sessionId, projectName, filePath });
        }
      }
    }
  }

  // ── Pass 2: aggregate ──────────────────────────────────────────────────────
  const { startDate, endDate, tzOffset = 0 } = opts;
  const sessionMap = new Map();
  const dailyMap = {};
  const modelMap = {};
  const hourlyMap = {};
  const allMessages = [];  // every message for costly queries / model queries
  const projectMap = {}; // projectName -> { cost, totalTokens, messages, sessions, toolCalls, models: Set }
  const sessionTimestampsAll = {}; // sessionId -> [timestamps] for rate-limit gap detection

  let totalCost = 0, totalInputTokens = 0, totalOutputTokens = 0;
  let totalCacheWrite = 0, totalCacheRead = 0, totalCacheReadSavings = 0, totalMessages = 0;

  for (const { entry, sessionId, projectName, filePath } of byUuid.values()) {
    const { usage, model } = entry.message;
    const timestamp = entry.timestamp;
    if (!timestamp) continue;

    const localMs = new Date(timestamp).getTime() - tzOffset * 60 * 1000;
    const _d = new Date(localMs);
    const date = `${_d.getUTCFullYear()}-${String(_d.getUTCMonth()+1).padStart(2,'0')}-${String(_d.getUTCDate()).padStart(2,'0')}`;
    if (startDate && date < startDate) continue;
    if (endDate && date > endDate) continue;

    const costs = calculateCost(usage, model);
    const hour = new Date(timestamp).getUTCHours();
    // Count tool_use blocks in this assistant message
    const toolCallCount = Array.isArray(entry.message.content)
      ? entry.message.content.filter(c => c.type === 'tool_use').length : 0;
    const inp = usage.input_tokens || 0;
    const out = usage.output_tokens || 0;
    const cw = usage.cache_creation_input_tokens || 0;
    const cr = usage.cache_read_input_tokens || 0;
    const total = inp + cw + cr + out;

    totalCost += costs.total;
    totalInputTokens += inp;
    totalOutputTokens += out;
    totalCacheWrite += cw;
    totalCacheRead += cr;
    totalCacheReadSavings += costs.cacheReadSavings;
    totalMessages++;

    // Track all timestamps per session (for rate-limit gap detection)
    if (!sessionTimestampsAll[sessionId]) sessionTimestampsAll[sessionId] = [];
    sessionTimestampsAll[sessionId].push(timestamp);

    // Session
    if (!sessionMap.has(sessionId)) {
      sessionMap.set(sessionId, {
        sessionId, projectName, filePath,
        cost: 0, inputTokens: 0, outputTokens: 0,
        cacheWrite: 0, cacheRead: 0, totalTokens: 0,
        messages: 0, toolCalls: 0, firstTimestamp: null, lastTimestamp: null,
        models: new Set(),
        firstPrompt: sessionFirstPrompt.get(sessionId) || '',
        totalPrompts: sessionPromptCount.get(sessionId) || 0,
        client: sessionClientMap.get(sessionId) || 'Terminal CLI',
      });
    }
    const sess = sessionMap.get(sessionId);
    sess.cost += costs.total;
    sess.inputTokens += inp;
    sess.outputTokens += out;
    sess.cacheWrite += cw;
    sess.cacheRead += cr;
    sess.totalTokens += total;
    sess.messages++;
    sess.toolCalls += toolCallCount;
    if (model) sess.models.add(model);
    if (!sess.firstTimestamp || timestamp < sess.firstTimestamp) sess.firstTimestamp = timestamp;
    if (!sess.lastTimestamp || timestamp > sess.lastTimestamp) sess.lastTimestamp = timestamp;

    // Daily
    if (!dailyMap[date]) dailyMap[date] = { cost: 0, inputTokens: 0, outputTokens: 0, cacheRead: 0, cacheWrite: 0, messages: 0, totalTokens: 0 };
    dailyMap[date].cost += costs.total;
    dailyMap[date].inputTokens += inp;
    dailyMap[date].outputTokens += out;
    dailyMap[date].cacheRead += cr;
    dailyMap[date].cacheWrite += cw;
    dailyMap[date].messages++;
    dailyMap[date].totalTokens += total;

    // Model
    const modelKey = model || 'unknown';
    if (!modelMap[modelKey]) modelMap[modelKey] = { cost: 0, inputTokens: 0, outputTokens: 0, cacheWrite: 0, cacheRead: 0, messages: 0, totalTokens: 0, sessions: new Set(), prompts: 0, toolCalls: 0 };
    modelMap[modelKey].cost += costs.total;
    modelMap[modelKey].inputTokens += inp;
    modelMap[modelKey].outputTokens += out;
    modelMap[modelKey].cacheWrite += cw;
    modelMap[modelKey].cacheRead += cr;
    modelMap[modelKey].messages++;
    modelMap[modelKey].totalTokens += total;
    // Resolve user prompt for this assistant entry (needed for model prompt count)
    const parentUserEntry = userByUuid.get(entry.parentUuid) || userByUuid.get(entry.uuid);
    let promptSnippet = '';
    let isAutomated = false;
    if (parentUserEntry?.message?.content) {
      const raw = cleanIdeSelection(extractText(parentUserEntry.message.content).replace(/\s+/g, ' ').trim());
      const label = automationLabel(raw);
      if (label) {
        promptSnippet = label;
        isAutomated = true;
      } else {
        promptSnippet = raw.slice(0, 200);
      }
    }

    modelMap[modelKey].sessions.add(sessionId);
    modelMap[modelKey].toolCalls += toolCallCount;
    if (!isAutomated && promptSnippet) modelMap[modelKey].prompts++;

    // Hourly
    if (!hourlyMap[hour]) hourlyMap[hour] = { cost: 0, messages: 0 };
    hourlyMap[hour].cost += costs.total;
    hourlyMap[hour].messages++;

    // Project
    if (!projectMap[projectName]) projectMap[projectName] = { cost: 0, totalTokens: 0, messages: 0, sessions: new Set(), toolCalls: 0, models: new Set() };
    projectMap[projectName].cost += costs.total;
    projectMap[projectName].totalTokens += total;
    projectMap[projectName].messages++;
    projectMap[projectName].sessions.add(sessionId);
    projectMap[projectName].toolCalls += toolCallCount;
    if (model) projectMap[projectName].models.add(model);

    const wordCount = promptSnippet ? promptSnippet.split(/\s+/).filter(Boolean).length : 0;
    const tokenDensity = wordCount > 3 ? Math.round(total / wordCount) : 0;
    const isBloated = inp > 12000 && out < inp * 0.06;
    allMessages.push({
      sessionId, projectName, timestamp, model: modelKey,
      cost: costs.total, inputTokens: inp, outputTokens: out,
      cacheWrite: cw, cacheRead: cr, totalTokens: total,
      prompt: promptSnippet, isAutomated, toolCalls: toolCallCount,
      tokenDensity, isBloated,
    });
  }

  // Serialize sessions
  const sessions = Array.from(sessionMap.values()).map(s => ({
    ...s,
    models: Array.from(s.models),
    durationMs: s.firstTimestamp && s.lastTimestamp ? new Date(s.lastTimestamp) - new Date(s.firstTimestamp) : 0,
  })).sort((a, b) => b.cost - a.cost);

  const totalAllTokens = totalInputTokens + totalCacheWrite + totalCacheRead + totalOutputTokens;
  const cacheHitRate = totalAllTokens > 0 ? Math.round((totalCacheRead / totalAllTokens) * 100) : 0;
  const zeroCacheSessions = sessions.filter(s => s.cacheRead === 0).length;

  // Cache efficiency score: what % of token reads came from cache vs fresh input
  const cacheEfficiencyScore = (totalCacheRead + totalInputTokens) > 0
    ? Math.round(totalCacheRead / (totalCacheRead + totalInputTokens) * 100) : 0;

  // 5-hour billing window (always based on real wall-clock time, not filtered date range)
  const nowMs = Date.now();
  const windowStartMs = nowMs - 5 * 60 * 60 * 1000;
  let windowCost = 0, windowTokens = 0, windowMessages = 0, windowOldestTs = null;
  for (const { entry } of byUuid.values()) {
    const ts = entry.timestamp ? new Date(entry.timestamp).getTime() : 0;
    if (ts >= windowStartMs && ts <= nowMs) {
      const c = calculateCost(entry.message.usage, entry.message.model);
      windowCost += c.total;
      const u = entry.message.usage;
      windowTokens += (u.input_tokens || 0) + (u.output_tokens || 0)
        + (u.cache_creation_input_tokens || 0) + (u.cache_read_input_tokens || 0);
      windowMessages++;
      if (!windowOldestTs || ts < windowOldestTs) windowOldestTs = ts;
    }
  }
  const currentWindow = {
    cost: windowCost, tokens: windowTokens, messages: windowMessages, windowHours: 5,
    oldestTs: windowOldestTs ? new Date(windowOldestTs).toISOString() : null,
  };

  // Rate limit event detection: gaps >=20 min and <8h within same session
  const rateLimitEvents = [];
  for (const [sid, timestamps] of Object.entries(sessionTimestampsAll)) {
    timestamps.sort();
    for (let i = 1; i < timestamps.length; i++) {
      const gapMin = (new Date(timestamps[i]) - new Date(timestamps[i - 1])) / 60000;
      if (gapMin >= 20 && gapMin < 480) {
        const sess = sessionMap.get(sid);
        rateLimitEvents.push({
          sessionId: sid,
          projectName: sess ? sess.projectName : '',
          gapMinutes: Math.round(gapMin),
          timestamp: timestamps[i],
        });
      }
    }
  }
  rateLimitEvents.sort((a, b) => b.timestamp.localeCompare(a.timestamp));

  // Top 20 by cost — real user queries first, then automated
  const topMessagesByCost = [
    ...[...allMessages].filter(m => !m.isAutomated).sort((a, b) => b.cost - a.cost),
    ...[...allMessages].filter(m => m.isAutomated).sort((a, b) => b.cost - a.cost),
  ].slice(0, 20);

  const dailySeries = Object.entries(dailyMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, d]) => ({ date, ...d }));

  // Forecasting: use last 7 days to project 30-day spend
  const recentDays = dailySeries.slice(-7);
  const avgDailySpend = recentDays.length > 0 ? recentDays.reduce((s, d) => s + d.cost, 0) / recentDays.length : 0;
  const forecast30d = avgDailySpend * 30;

  // Anomaly detection
  const avgDailyCost = dailySeries.length > 0 ? dailySeries.reduce((s, d) => s + d.cost, 0) / dailySeries.length : 0;
  const anomalyDays = dailySeries.filter(d => d.cost > avgDailyCost * 2.5 && d.cost > 0.01).map(d => ({ date: d.date, cost: d.cost, ratio: d.cost / avgDailyCost }));

  const modelBreakdown = Object.entries(modelMap)
    .sort(([, a], [, b]) => b.cost - a.cost)
    .map(([model, d]) => ({ model, ...d, sessions: d.sessions.size }));

  // Model queries: ALL messages per model, non-automated sorted first.
  // The API returns them all; the UI paginates with a "Show more" button.
  const modelQueries = {};
  for (const { model } of modelBreakdown) {
    const msgs = allMessages.filter(m => m.model === model);
    modelQueries[model] = [
      ...msgs.filter(m => !m.isAutomated).sort((a, b) => b.totalTokens - a.totalTokens),
      ...msgs.filter(m => m.isAutomated).sort((a, b) => b.totalTokens - a.totalTokens),
    ];
  }

  const hourlySeries = Array.from({ length: 24 }, (_, h) => ({
    hour: h, ...(hourlyMap[h] || { cost: 0, messages: 0 }),
  }));

  const insights = generateInsights({
    sessions, dailySeries,
    topMessages: topMessagesByCost,
    totalCost, totalMessages, totalCacheRead,
    totalCacheReadSavings, cacheHitRate,
    totalAllTokens, totalOutputTokens,
    anomalyDays, avgDailyCost, modelBreakdown,
  });

  return {
    summary: {
      totalCost, totalInputTokens, totalOutputTokens,
      totalCacheWrite, totalCacheRead, totalCacheReadSavings,
      totalAllTokens, cacheHitRate,
      totalMessages, totalSessions: sessions.length,
      totalProjects: new Set(sessions.map(s => s.projectName)).size,
      costPerMessage: totalMessages > 0 ? totalCost / totalMessages : 0,
      avgTokensPerSession: sessions.length > 0 ? Math.round(totalAllTokens / sessions.length) : 0,
      zeroCacheSessions,
      forecast30d,
      avgDailySpend,
      cacheEfficiencyScore,
      currentWindow,
      rateLimitEventCount: rateLimitEvents.length,
    },
    sessions: sessions.slice(0, 50),
    dailySeries,
    modelBreakdown,
    modelQueries,
    hourlySeries,
    topMessages: topMessagesByCost,
    insights,
    rateLimitEvents: rateLimitEvents.slice(0, 20),
    projects: Object.entries(projectMap)
      .sort(([, a], [, b]) => b.cost - a.cost)
      .map(([name, d]) => ({ name, ...d, sessions: d.sessions.size, models: Array.from(d.models) })),
  };
}

/**
 * Returns all turns for a specific session file.
 * A "turn" = one real user text message + all assistant API calls that follow it
 * (before the next user text message).
 */
function getSessionDetail(filePath) {
  if (!fs.existsSync(filePath)) return { turns: [], summary: null };
  const entries = parseJsonlFile(filePath).sort((a, b) => {
    if (!a.timestamp) return -1;
    if (!b.timestamp) return 1;
    return a.timestamp.localeCompare(b.timestamp);
  });

  // Build UUID lookup
  const byUuid = new Map();
  for (const e of entries) {
    if (e.uuid) {
      // Keep highest-output version
      const ex = byUuid.get(e.uuid);
      const newOut = e.message?.usage?.output_tokens || 0;
      const oldOut = ex?.message?.usage?.output_tokens || -1;
      if (newOut >= oldOut) byUuid.set(e.uuid, e);
    }
  }

  const turns = [];
  let currentTurn = null;

  for (const entry of entries) {
    if (isUserTextMessage(entry)) {
      if (currentTurn) turns.push(currentTurn);
      currentTurn = {
        turnNumber: turns.length + 1,
        userPrompt: cleanIdeSelection(extractText(entry.message.content).replace(/\s+/g, ' ').trim()).slice(0, 400),
        timestamp: entry.timestamp,
        model: null,
        inputTokens: 0, outputTokens: 0,
        cacheWrite: 0, cacheRead: 0, totalTokens: 0,
        cost: 0, apiCalls: 0, toolCalls: 0,
      };
    } else if (entry.type === 'assistant' && entry.message?.usage && currentTurn) {
      // Only count deduplicated entries
      const deduped = byUuid.get(entry.uuid);
      if (deduped !== entry) continue;

      const u = entry.message.usage;
      const inp = u.input_tokens || 0;
      const out = u.output_tokens || 0;
      const cw = u.cache_creation_input_tokens || 0;
      const cr = u.cache_read_input_tokens || 0;
      const costs = calculateCost(u, entry.message.model);

      const turnToolCalls = Array.isArray(entry.message.content)
        ? entry.message.content.filter(c => c.type === 'tool_use').length : 0;
      currentTurn.inputTokens += inp;
      currentTurn.outputTokens += out;
      currentTurn.cacheWrite += cw;
      currentTurn.cacheRead += cr;
      currentTurn.totalTokens += inp + cw + cr + out;
      currentTurn.cost += costs.total;
      currentTurn.apiCalls++;
      currentTurn.toolCalls += turnToolCalls;
      if (entry.message.model) currentTurn.model = entry.message.model;
    }
  }
  if (currentTurn) turns.push(currentTurn);

  const totalCost = turns.reduce((s, t) => s + t.cost, 0);
  const totalTokens = turns.reduce((s, t) => s + t.totalTokens, 0);
  const totalCacheRead = turns.reduce((s, t) => s + t.cacheRead, 0);
  const cacheHitRate = totalTokens > 0 ? Math.round((totalCacheRead / totalTokens) * 100) : 0;
  const avgCostPerTurn = turns.length > 0 ? totalCost / turns.length : 0;

  // Efficiency judgement
  let efficient = false;
  let efficiencyNote = '';
  if (turns.length > 0) {
    if (cacheHitRate >= 70) {
      efficient = true;
      efficiencyNote = `${turns.length} turns, avg ${fmt$(avgCostPerTurn)}/turn, total ${fmt$(totalCost)}. Cache hit rate: ${cacheHitRate}%. Cache is working well.`;
    } else {
      efficiencyNote = `${turns.length} turns, avg ${fmt$(avgCostPerTurn)}/turn, total ${fmt$(totalCost)}. Cache hit rate: ${cacheHitRate}%. Consider using /clear between unrelated tasks.`;
    }
  }

  return {
    turns,
    summary: {
      totalTurns: turns.length,
      totalCost,
      totalTokens,
      cacheHitRate,
      efficient,
      efficiencyNote,
    },
  };
}

function fmt$(n) {
  if (!n || n < 0.0001) return '$0.00';
  if (n < 0.01) return `$${n.toFixed(5)}`;
  if (n < 1) return `$${n.toFixed(4)}`;
  return `$${n.toFixed(2)}`;
}

function fmtTokens(n) {
  if (!n) return '0';
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

function generateInsights({ sessions, dailySeries, topMessages, totalCost, totalMessages,
  totalCacheRead, totalCacheReadSavings, cacheHitRate, totalAllTokens, totalOutputTokens,
  anomalyDays = [], avgDailyCost = 0, modelBreakdown = [] }) {

  const tips = [];

  if (totalAllTokens > 0) {
    const outputPct = ((totalOutputTokens / totalAllTokens) * 100).toFixed(1);
    tips.push({
      icon: '💬',
      title: `${outputPct}% of tokens are Claude actually writing`,
      summary: `Only ${outputPct}% of all tokens are Claude's output. The rest is context Claude reads.`,
      detail: `Every message you send causes Claude to re-read the entire conversation from scratch. In a 3-message conversation, the 3rd message processes ~3× more tokens than the 1st. Use /clear when switching tasks to avoid paying to re-read irrelevant history.`,
    });
  }

  if (cacheHitRate >= 80) {
    tips.push({
      icon: '💾',
      title: `${cacheHitRate}% cache hit rate — excellent!`,
      summary: `${cacheHitRate}% of your tokens were served from cache, saving you ${fmt$(totalCacheReadSavings)}.`,
      detail: `Prompt caching charges only 10% of the normal input rate for repeated context. Your ${cacheHitRate}% cache hit rate means you're efficiently reusing context. Cache writes cost 1.25× input but only happen once per unique context block.`,
    });
  } else if (totalCacheReadSavings > 0.01) {
    tips.push({
      icon: '💾',
      title: 'Prompt caching is saving you money',
      summary: `You've saved ${fmt$(totalCacheReadSavings)} through cache hits (${cacheHitRate}% rate).`,
      detail: `Cache reads cost 10× less than normal input. Your cache hit rate is ${cacheHitRate}% — there's room to improve by keeping sessions focused on one topic so more context gets reused.`,
    });
  }

  const top3Cost = sessions.slice(0, 3).reduce((s, x) => s + x.cost, 0);
  if (sessions.length >= 3 && totalCost > 0) {
    const pct = Math.round((top3Cost / totalCost) * 100);
    if (pct >= 50) {
      tips.push({
        icon: '🔥',
        title: 'The longer you chat, the more each message costs',
        summary: `Your 3 costliest sessions account for ${pct}% of total spend.`,
        detail: `Long conversations compound: each new message re-reads every previous exchange. A 100-message session can cost 50× more per message than a fresh 2-message session for the same question. Use /clear to start fresh when switching tasks.`,
      });
    }
  }

  if (topMessages.length > 0) {
    const vague = topMessages.filter(m => m.prompt && m.prompt.length < 25 && m.totalTokens > 5000);
    if (vague.length > 0) {
      tips.push({
        icon: '⚡',
        title: 'Short, vague messages are costing you the most',
        summary: `${vague.length} of your top queries are short follow-ups with large context.`,
        detail: `Messages like "yes", "do it", or "continue" carry the full conversation context but give Claude very little new guidance. Starting a new session with a complete, specific prompt is often cheaper and produces better results.`,
      });
    }
  }

  if (dailySeries.length > 0) {
    const busiest = [...dailySeries].sort((a, b) => b.cost - a.cost)[0];
    tips.push({
      icon: '📅',
      title: `Peak day: ${busiest.date}`,
      summary: `${fmt$(busiest.cost)} spent on ${busiest.date} across ${busiest.messages} API calls.`,
      detail: `Heavy usage days suggest marathon coding sessions. These are expensive because each tool call adds to an ever-growing context. Consider breaking large tasks into separate Claude Code sessions rather than one continuous conversation.`,
    });
  }

  tips.push({
    icon: '🧠',
    title: 'Model choice significantly impacts cost',
    summary: 'Opus costs 5× more than Sonnet and 18× more than Haiku per token.',
    detail: `Pricing per 1M tokens: Opus $15 input/$75 output, Sonnet $3/$15, Haiku $0.80/$4. For routine tasks like file editing, code completion, and simple Q&A, Haiku or Sonnet deliver excellent results at a fraction of the cost. Reserve Opus for complex multi-step reasoning.`,
  });

  // Anomaly detection
  if (anomalyDays.length > 0) {
    const top = anomalyDays[0];
    tips.push({
      icon: '🚨',
      title: `Anomaly: ${top.date} spent ${top.ratio.toFixed(1)}× the daily average`,
      summary: `${fmt$(top.cost)} on ${top.date} vs ${fmt$(avgDailyCost)} daily avg.`,
      detail: `This spike is likely due to a large context window session or many rapid iterations. Check the Sessions tab filtered to that date to identify the culprit.`,
    });
  }

  // Context bloat detection
  const bloatySessions = sessions.filter(s => s.messages > 5 && s.totalTokens / s.messages > 50000);
  if (bloatySessions.length > 0) {
    tips.push({
      icon: '📦',
      title: `${bloatySessions.length} sessions have context bloat`,
      summary: `Average context >50K tokens/message — each reply re-reads a huge history.`,
      detail: `Use /clear between distinct tasks. Session "${bloatySessions[0].firstPrompt?.slice(0, 40) || bloatySessions[0].sessionId.slice(0, 8)}" had avg ${fmtTokens(Math.round(bloatySessions[0].totalTokens / bloatySessions[0].messages))} tokens per message.`,
    });
  }

  // Opus cost optimisation — use modelBreakdown for accurate per-model cost
  const opusEntry = modelBreakdown.find(m => m.model.includes('opus'));
  if (opusEntry && opusEntry.cost > 0) {
    const sonnetEntry = modelBreakdown.find(m => m.model.includes('sonnet'));
    const potentialSaving = opusEntry.cost * 0.8; // ~80% savings switching to Sonnet
    tips.push({
      icon: '💡',
      title: `${fmt$(opusEntry.cost)} spent on Opus — could save ~${fmt$(potentialSaving)} with Sonnet`,
      summary: `Opus costs 5× more than Sonnet. ${opusEntry.messages.toLocaleString()} Opus API calls recorded.`,
      detail: `For file editing, code explanation, and simple Q&A, Sonnet provides near-identical results at 5× less cost. ${sonnetEntry ? `You already use Sonnet (${sonnetEntry.messages.toLocaleString()} calls). ` : ''}Reserve Opus for multi-step planning and complex architecture decisions.`,
    });
  }

  return tips;
}

module.exports = { buildAnalytics, getSessionDetail, findSessionFiles, CLAUDE_DIR };
